# GitHub Security Configuration
# This file configures security settings for the repository

# Security Advisories
security_advisories:
  enabled: true
  private_disclosure: true
  credit_developers: true

# Code Scanning
code_scanning:
  enabled: true
  languages:
    - java
  tools:
    - codeql
    - semgrep

# Secret Scanning
secret_scanning:
  enabled: true
  push_protection: true
  validate_git_push: true

# Dependency Scanning
dependency_scanning:
  enabled: true
  auto_fix: true
  security_updates: true

# Branch Protection
branch_protection:
  main:
    required_status_checks:
      strict: true
      contexts:
        - "Security Scan"
        - "CodeQL"
    enforce_admins: true
    required_pull_request_reviews:
      required_approving_review_count: 1
      dismiss_stale_reviews: true
      require_code_owner_reviews: true
    restrictions:
      users: []
      teams: []

# Security Headers
security_headers:
  content_security_policy: "default-src 'self'"
  x_frame_options: "DENY"
  x_content_type_options: "nosniff"
  referrer_policy: "strict-origin-when-cross-origin"

# Vulnerability Disclosure
vulnerability_disclosure:
  policy: "coordinated"
  timeline:
    initial_response: "48h"
    status_update: "7d"
    resolution: "30d"
  contact:
    email: "security@example.com"
    pgp_key: ""

# Security Monitoring
monitoring:
  failed_logins: true
  suspicious_activity: true
  dependency_vulnerabilities: true
  secret_exposure: true

# Compliance
compliance:
  gdpr: true
  ccpa: true
  sox: false
  hipaa: false
