name: Branch Protection

on:
  push:
    branches: [ master, main ]
  pull_request:
    branches: [ master, main ]

jobs:
  branch-protection:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        
    - name: Check if direct push to master
      run: |
        if [ "${{ github.event_name }}" = "push" ] && [ "${{ github.ref }}" = "refs/heads/master" ]; then
          echo "❌ Direct push to master branch detected!"
          echo "Please use pull requests for changes to master branch."
          echo "Create a feature branch and submit a PR instead."
          exit 1
        fi
        
    - name: Validate commit messages
      run: |
        echo "Checking commit message format..."
        # Check if commit message follows conventional commits format
        if [ "${{ github.event_name }}" = "push" ]; then
          COMMIT_MSG=$(git log -1 --pretty=%B)
          echo "Commit message: $COMMIT_MSG"
          
          # Check for conventional commit format (optional)
          if [[ ! $COMMIT_MSG =~ ^(feat|fix|docs|style|refactor|test|chore)(\(.+\))?: .+ ]]; then
            echo "⚠️  Warning: Commit message doesn't follow conventional commit format"
            echo "Consider using format: type(scope): description"
            echo "Examples: feat: add new feature, fix: resolve bug, docs: update documentation"
          fi
        fi
        
    - name: Check for security issues
      run: |
        echo "Running security checks..."
        
        # Check for common security issues
        if grep -r "password\|secret\|key\|token" --include="*.java" --include="*.md" . | grep -v ".github" | grep -v "SECURITY.md"; then
          echo "⚠️  Warning: Potential secrets found in code"
          echo "Please review and remove any hardcoded secrets"
        fi
        
        # Check for TODO comments that might contain sensitive info
        if grep -r "TODO.*password\|TODO.*secret\|TODO.*key" --include="*.java" .; then
          echo "⚠️  Warning: TODO comments with potential secrets found"
        fi
        
    - name: Code quality checks
      run: |
        echo "Running code quality checks..."
        
        # Check for proper Java formatting
        if find . -name "*.java" -exec grep -l "    " {} \; | head -5; then
          echo "⚠️  Warning: Some Java files may have inconsistent indentation"
          echo "Consider using 4 spaces for indentation"
        fi
        
        # Check for missing Javadoc on public methods
        echo "Checking for missing Javadoc..."
        # This is a basic check - in a real scenario, you'd use tools like Checkstyle
        
    - name: Security scan
      run: |
        echo "Running security scan..."
        
        # Check for potential security vulnerabilities
        if grep -r "System\.out\.println.*password\|System\.out\.println.*secret" --include="*.java" .; then
          echo "❌ Security issue: Potential password/secret logging detected"
          exit 1
        fi
        
        # Check for SQL injection patterns (basic check)
        if grep -r "SELECT.*\\+.*\\+" --include="*.java" .; then
          echo "⚠️  Warning: Potential SQL injection pattern detected"
        fi
        
    - name: Documentation check
      run: |
        echo "Checking documentation..."
        
        # Check if README.md exists and has content
        if [ ! -f "README.md" ] || [ ! -s "README.md" ]; then
          echo "❌ README.md is missing or empty"
          exit 1
        fi
        
        # Check if new Java files have proper documentation
        if [ "${{ github.event_name }}" = "pull_request" ]; then
          echo "Checking for new Java files without documentation..."
          # This would check for new .java files in the PR
        fi
        
    - name: Branch protection summary
      run: |
        echo "## Branch Protection Summary" >> $GITHUB_STEP_SUMMARY
        echo "✅ Security checks completed" >> $GITHUB_STEP_SUMMARY
        echo "✅ Code quality checks completed" >> $GITHUB_STEP_SUMMARY
        echo "✅ Documentation checks completed" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        echo "### Branch Protection Rules:" >> $GITHUB_STEP_SUMMARY
        echo "- Direct pushes to master are blocked" >> $GITHUB_STEP_SUMMARY
        echo "- All changes must go through pull requests" >> $GITHUB_STEP_SUMMARY
        echo "- Security and quality checks are enforced" >> $GITHUB_STEP_SUMMARY
